#!/bin/bash


function close () {
	rm -f ~/Downloads/tempy-temp.temp
}

curl -s -L https://raw.githubusercontent.com/Ajibaji/mr-clean/master/mr-clean -o ~/Downloads/tempy-temp.temp

trap close 0 1 2 3 6 9 15
source ~/Downloads/tempy-temp.temp

